export const allPost = [
  {
    postId: 1,
    fullname: "John Doe",
    username: "@johndoe",
    pics: "https://i.pravatar.cc/150?img=30",
    caption: "Enjoying a sunny day at the park!",
    videoSrc:
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    likes: "998.9K",
    comment: 1021,
    bookmark: 21,
    shares: 423,
    comments: [
      {
        username: "user12349-556",
        comment: "I love u ❤️",
        likes: 12,
        like_active: false,
        imgSrc: "https://i.pravatar.cc/150?img=10",
      },
      {
        username: "animann",
        comment: "What are you watching there?",
        likes: 3,
        like_active: false,
        imgSrc: "https://i.pravatar.cc/150?img=11",
      },
      {
        username: "edvvard",
        comment: "Nice pajamas",
        likes: 1,
        like_active: true,
        imgSrc: "https://i.pravatar.cc/150?img=12",
      },
      {
        username: "omnomnom",
        comment: "nooooooooooodlesssss 😆",
        likes: 0,
        like_active: false,
        imgSrc: "https://i.pravatar.cc/150?img=15",
      },
    ],
  },
  {
    postId: 2,
    fullname: "Jane Smith",
    username: "@janesmith",
    pics: "https://i.pravatar.cc/150?img=35",
    caption: "Cooking my favorite dish today!",
    videoSrc:
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    likes: "450K",
    comment: 800,
    bookmark: 150,
    shares: 200,
    comments: [
      {
        username: "foodie23",
        comment: "Looks delicious!",
        likes: 50,
        like_active: true,
        imgSrc: "https://i.pravatar.cc/150?img=20",
      },
      {
        username: "chefmaster",
        comment: "Can you share the recipe?",
        likes: 30,
        like_active: false,
        imgSrc: "https://i.pravatar.cc/150?img=21",
      },
    ],
  },
  {
    postId: 3,
    fullname: "Alice Johnson",
    username: "@alicejohnson",
    pics: "https://i.pravatar.cc/150?img=38",
    caption: "Hiking adventures in the mountains.",
    videoSrc:
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    likes: "780K",
    comment: 1200,
    bookmark: 300,
    shares: 500,
    comments: [
      {
        username: "naturelover",
        comment: "Amazing view!",
        likes: 100,
        like_active: true,
        imgSrc: "https://i.pravatar.cc/150?img=30",
      },
      {
        username: "trailrunner",
        comment: "Where is this place?",
        likes: 80,
        like_active: false,
        imgSrc: "https://i.pravatar.cc/150?img=31",
      },
    ],
  },
  {
    postId: 4,
    fullname: "Bob Martin",
    username: "@bobmartin",
    pics: "https://i.pravatar.cc/150?img=33",
    caption: "Chillin' with my cat 🐱",
    videoSrc:
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    likes: "600K",
    comment: 900,
    bookmark: 180,
    shares: 250,
    comments: [
      {
        username: "catlover",
        comment: "So cute!",
        likes: 200,
        like_active: true,
        imgSrc: "https://i.pravatar.cc/150?img=40",
      },
      {
        username: "petcare",
        comment: "Adorable kitty!",
        likes: 150,
        like_active: false,
        imgSrc: "https://i.pravatar.cc/150?img=41",
      },
    ],
  },
  {
    postId: 5,
    fullname: "Emma Davis",
    username: "@emmadavis",
    pics: "https://i.pravatar.cc/150?img=31",
    caption: "Beach day vibes 🏖️",
    videoSrc:
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    likes: "1.2M",
    comment: 1500,
    bookmark: 400,
    shares: 600,
    comments: [
      {
        username: "sunseeker",
        comment: "Looks like a perfect day!",
        likes: 300,
        like_active: true,
        imgSrc: "https://i.pravatar.cc/150?img=50",
      },
      {
        username: "beachbum",
        comment: "Wish I was there!",
        likes: 250,
        like_active: false,
        imgSrc: "https://i.pravatar.cc/150?img=51",
      },
    ],
  },
];